id: A6612C426
title: 'The Yearning Song that Swiftly Inspires Compassion: A Prayer to the Vajradhara
  Gurus, the Gentle Protectors'
type: translation
pechas:
- I642241AF
- ID4845D14
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:36:14.655739
  last_modified_at: 2023-01-04 12:36:14.655743
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I642241AF/21D1: '4663'
  ID4845D14/3FFA: '4663'
